server:
  port: 3000

database:
  postgres:
    host: localhost
    port: 5432
    user: hoangnx30
    password: Matkhaulan#1
    database: postgres

jwt: 
  secret: your-super-secret-key-change-in-production
  expiration: 3600
