module.exports.prettierConfig = {
  endOfLine: "lf",
  tabWidth: 2,
  printWidth: 120,
  useTabs: false,
  semi: false,
  bracketSpacing: false,
  singleQuote: true,
  trailingComma: "none",
  importOrderParserPlugins: ["typescript", "decorators-legacy"],
  // importOrder: [
  //   "^@/packages/(.*)$",
  //   "^@/auth/(.*)$",
  //   "^@/aws/(.*)$",
  //   "^@/common/(.*)$",
  //   "^@/company/(.*)$",
  //   "^@/corp-billing/(.*)$",
  //   "^@/cron-job/(.*)$",
  //   "^@/employee/(.*)$",
  //   "^@/group/(.*)$",
  //   "^@/ibs/(.*)$",
  //   "^@/master-data/(.*)$",
  //   "^@/migration/(.*)$",
  //   "^@/onelogin/(.*)$",
  //   "^@/pax-app/(.*)$",
  //   "^@/policy/(.*)$",
  //   "^@/trip/(.*)$",
  //   "^@/user/(.*)$",
  //   "^@/setting/(.*)$",
  //   "^[./]",
  // ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: [
    require.resolve("prettier-plugin-packagejson"),
    require.resolve("@trivago/prettier-plugin-sort-imports"),
  ],
};
